export const ROUTES = {
  AUTH: {
    LOGIN: '/login',
    RESET_PASSWORD: '/reset-password',
    UNAUTHORIZED: '/unauthorized',
    ACCOUNT_DISABLED: '/account-disabled',
  },
  DASHBOARD: '/',
  CUSTOMERS: '/customers',
  INVENTORY: {
    ROOT: '/inventory',
    PRODUCTS: '/inventory/products',
    STOCK: '/inventory/stock',
    CATEGORIES: '/inventory/categories',
    BRANDS: '/inventory/brands',
    SUPPLIERS: '/inventory/suppliers',
  },
  SALES: '/sales',
  REPAIRS: {
    ROOT: '/repairs',
    JOB_CARDS: '/repairs/job-cards',
    SERVICE_HISTORY: '/repairs/service-history',
    REPAIR_STATUS: '/repairs/repair-status',
    WARRANTY: '/repairs/warranty',
    SPARE_PARTS: '/repairs/spare-parts-used',
  },
  TECHNICIANS: '/technicians',
  EXPENSES: '/expenses',
  PAYMENTS: '/payments',
  REPORTS: '/reports',
  ANALYTICS: '/analytics',
  NOTIFICATIONS: '/notifications',
  SETTINGS: '/settings',
  BACKUP: '/backup',
  ACTIVITY_LOG: '/activity-log',
  PROFILE: '/profile',
} as const;
